version: '3.8'

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "5000:5000"
    depends_on:
      - user-service
      - recipe-service
      - order-service
      - notification-service
      - delivery-service

  user-service:
    build: ./user-service
    ports:
      - "5001:5001"
    volumes:
      - ./user-service:/usr/src/app
    environment:
      - PORT=5001
      - MONGO_URI=mongodb://mongo:27017/foodwaste_users
      - JWT_SECRET=supersecret
    depends_on:
      - mongo

  recipe-service:
    build: ./recipe-service
    ports:
      - "5002:5002"
    volumes:
      - ./recipe-service:/usr/src/app
    environment:
      - PORT=5002
      - MONGO_URI=mongodb://mongo:27017/foodwaste_recipes
    depends_on:
      - mongo

  order-service:
    build: ./order-service
    ports:
      - "5003:5003"
    volumes:
      - ./order-service:/usr/src/app
    environment:
      - PORT=5003
      - MONGO_URI=mongodb://mongo:27017/foodwaste_orders
    depends_on:
      - mongo

  notification-service:
    build: ./notification-service
    ports:
      - "5004:5004"
    volumes:
      - ./notification-service:/usr/src/app
    environment:
      - PORT=5004
      - MONGO_URI=mongodb://mongo:27017/foodwaste_notifications
    depends_on:
      - mongo

  delivery-service:
    build: ./delivery-service
    ports:
      - "5005:5005"
    volumes:
      - ./delivery-service:/usr/src/app
    environment:
      - PORT=5005
      - MONGO_URI=mongodb://mongo:27017/foodwaste_delivery
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - api-gateway

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
